- etc/insights-client.spec
- setup.py
This just adds it as another entry point.  Adding `redhat-access-insights` to the `%files` section tells RPM to not delete the file when uninstalling the old `redhat-access-insights` package.
> Properly add legacy redhat-access-insights executable

- .flake8
- etc/insights-client.spec
This can be removed now that the client no longer reads yaml for config.
See https://github.com/RedHatInsights/insights-core/pull/731 as well
> Remove PyYAML RPM dependency

- etc/insights-client.spec
python-six will be required for Python 3 support, and python-magic is
what we want to use for libmagic bindings in RHEL.
> Add python-six and python-magic RPM dependencies

- MANIFEST.rhel6
- MANIFEST.rhel7
- Makefile
- etc/insights-client.service
- etc/insights-client.spec
- etc/insights-client.timer
- insights_client/__init__.py
- insights_client/major_version.py
- major_version.py
- setup.py
One thing to note is that I'm doing a `sysemctl daemon-reload` when uninstalling on RHEL 7.  Not sure if this is okay to do, but otherwise I get `Access denied` errors when running `systemctl status insights-client` after uninstallation.
> Use systemd timer instead of cron on RHEL 7 and up

- insights_client/__init__.py
Hello.
When trying to run insights-client on system with only Python 3, I found one incompatibility.
When the first argument to `map` function is `None` it
* is no-op in Python 2
* raises a `TypeError` in Python 3 because `None` is not callable
Original error:
```
Traceback (most recent call last):
File "__init__.py", line 175, in <module>
_main()
File "__init__.py", line 122, in _main
if not all(map(None, [insights_uid, insights_gid, insights_grpid])):
TypeError: 'NoneType' object is not callable
```
So I think that it's a good idea to remove `map`.
> Fix Python 3 incompatibility and remove unnecessary `map`

- etc/insights-client.spec
Need to remove etag so that egg can be updated on reinstall
https://bugzilla.redhat.com/show_bug.cgi?id=1591371
> remove etag on uninstall (BZ1591371)

- README.md
Before this fix, the README shows all switches in the same line. 
This is meant to fix that and format it in a more readable way.
> Format CLI switches properly in Markdown

- docs/insights-client.8
- etc/insights-client.motd
- etc/insights-client.spec
- insights_client/__init__.py
- setup.py
Insights represents key functionality of the RHEL operating system. Customers are missing out on Value of Subscription when not enabled. Thus we display a message in motd when Insights is installed but has never been used.
We use a ```/etc/motd.d/``` drop in file to do this. Once insights-client has been
used (and a new egg has been retrieved) we drop this message.
The message can be edited or removed in the configuration file:
/etc/insights-client/insights-client.motd
This motd message seems to represent part of the insights-client command-line
RPM packaged wrapper of InsightsClient and is less suited to the core functionality.
> Display a message in motd Insights has not yet been used

- etc/insights-client.spec
- insights_client/__init__.py
Once insights-client has been used, we remove the message in
motd recommending use of Insights. Instead of removing the symlink
we instead point it at /dev/null.
We also need to be careful for upgrades. Upgrading the
insights-client package on a system where Insights has already
been used should not result in a motd message.
> Point the motd message at /dev/null instead of removing

- etc/insights-client.spec
If insights-client has been used, then don't install the motd
message. As before don't install a motd message if such a symlink
already exists.
Further testing of the latest builds resulted in this fix.
> Don't install the motd message if insights-client used

- insights_client/run.py
This will result in slightly more useful exit messages:
`Error importing insights.client for collect_and_output as /home/cloud-user/Projects/RedHatInsights/insights-core: No module named 'distro'`
> Include caught `ImportError` exception in exit message

- etc/insights-client.service
In the case of the system not having cgroups enabled, these
ExecStartPost commands will not cause the unit to fail (because they are
prefixed with "-"). If cgroups are enabled, they will set the limits
appropriately. Either way, no errors will be logged to the journal (such
as "No such file or directory" errors) due to the stderr redirection).
> Silently attempt writing to cgroup memory limits

- MANIFEST.rhel6
- etc/insights-client.cron
- etc/insights-client.spec
- etc/sysconfig/insights-client
- setup.py
Define a sysconfig file at /etc/sysconfig/insights-client. This file contains variables used by the cron script.
> Add a RANDOM_DELAY_SEC option to cron

- etc/insights-client.spec
This permits directory traversal and listing. This brings permissions in line with the rest of the `/var/log` directories.
> Create lib/ and log/ with executable bits

- etc/insights-client.timer
When enabled, the time when the service was last triggered is stored on disk. Now the client with be triggered if the host has been powered off since the last time the timer would have triggered.
Signed-off-by: Link Dupont <link@sub-pop.net>
> Enable timer persistence

- etc/insights-client.spec
- insights_client/__init__.py
- setup.py
Remove `insights-client-run` as a distributed "entrypoint". Since we don't want users running `insights-client-run` directly, it is not necessary to export as an public interface to the client. Instead, the main `insights-client` locates `run.py` in a relative directory to its own `__file__` path.
The results of `gpg_validate` are used to filter down a list to one of only valid eggs. If an egg does not exist and `BYPASS_GPG` is `True,` then the list will erroneously contain paths to eggs that do not exist. This ends up causing a later call to `Popen.communicate` to hang indefinitely. Moving the `BYPASS_GPG` check to below the file exists path avoids this.
**Note**: This PR obsoletes #92.
> Remove run entrypoint

- insights_client/__init__.py
Move the `exists()` check for ASCII-armored signature to after `BYPASS_GPG`. Checking for the presence of signature files is irrelevant if `BYPASS_GPG` is true, and having it earlier caused `False` to be erroneously returned before the bypass switch could return `True`.
> Change gpg_validate logic

- configure.ac
- data/cron/Makefile.am
- data/cron/insights-client
- data/cron/insights-client.cron
- data/systemd/Makefile.am
- data/systemd/insights-client-results.path.in
- data/systemd/insights-client-results.service.in
- data/systemd/insights-client.timer
Adds a systemd "path" unit that watches /etc/insights-client/.lastupload for modification. The unit it triggers then sleeps for 120 seconds (:frowning:) before running --check-update.
The Also= clause in insights-client.timer causes insights-client-results.path to be enabled when insights-client.timer is. This keeps the user experience "the same". Enabling just insights-client.timer will also enable insights-client-results.path. insights-client-results.path adds a PartOf= dependency to insights-client.timer, so that it is started and stopped when insights-client.timer is started.
The new ENABLE_CHECK_RESULTS variable in sysconfig enables this same functionality for cron-based systems.
> Add "insights-client-results.service"

- data/systemd/insights-client.timer
- Make timer depend on network-online, ensuring that network is up before starting
- Make timers.target start insights-client.timer rather than multi-user
Fixes: RHCLOUD-4398, RHBZ#1798373
> systemd: timer unit updates

- src/Makefile.am
- src/redhat-access-insights.in
Install a legacy compatibility script to support the deprecated 'redhat-access-insights' executable.
Fixes: RHCLOUD-5409
> legacy: add redhat-access-insights

- src/redhat-access-insights.in
Update the deprecation message when running redhat-access-insights to guide users to the new client name.
> Update deprecation message

- src/insights_client/__init__.py
I think this is commented out cause of a holdover from doing builds by OS ver.
The existing oserror will handle motd.d dir not existing e.g. on RHEL6 so we ought to be OK putting it in for all builds.
> uncomment motd function call

- data/cron/insights-client.cron
When a cron job generates output on stdout, it creates local mail messages in /var/spool/mail/root. This isn't necessary, especially for informational log messages like "Sleeping for N seconds". This PR removes the echo statement from the cron script.
Fixes: RHCLOUD-6140 RHBZ#1828778
> Remove echo from cron

- autogen.sh
- data/cron/insights-client.cron
- src/redhat-access-insights.in
Run cron script and redhat-access-insights script through shellcheck.
Fixes: RHCLOUD-6204
> Fix shellcheck warnings

- configure.ac
- data/systemd/80-insights.preset
- data/systemd/Makefile.am
- data/systemd/insights-register.path.in
- data/systemd/insights-register.service.in
- data/systemd/insights-unregister.path.in
- data/systemd/insights-unregister.service.in
Add a systemd path unit that watches for the existence of `/etc/pki/consumer/cert.pem` and `/etc/pki/consumer/key.pem`. If those files exist, the unit triggers a service that invokes `insights-client --register`. Upon successful execution of `insights-client --register`, the service unit masks the path unit, disabling it from further execution.
This unit is installed only if `insights-client` is built with the `--enable-auto-registration` flag. This flag defaults to 'no'. This installs two additional systemd unit files: `insights-register.path` and `insights-register.service`. Finally, `insights-register.path` must be enabled post installation. On systems that have been configured to use this auto-registration mechanism, in order to opt out of automatic registration, mask the path unit …
> Insights register

- src/insights_client/Makefile.am
- src/insights_client/constants.py.in
Add the common location variables, as generated by the `configure` script, to the generated constants.py file, so they are accessible within the program. This is the first in a long process of updating `insights-core.client.constants` to be able to use properly portable filesystem paths. Sadly, nothing in `insights-core` can use these paths until an RPM containing the generated constants file has been released on all RHEL distributions.
> constants: Add location variables to generated constants

- configure.ac
- data/Makefile.am
- src/insights_client/__init__.py
Currently, insights-client uses the presence of newest.egg to decide whether to preserve or remove the /etc/motd.d/insights-client snippet. For clients where auto_update is disabled, the newest.egg never gets created, leading to a false claim from the motd stating that the host is not registered, when in reality, it is.
This PR changes the logic of the `update_motd_message` function to use the registration stamp files. If either .registered or .unregistered exist, the symlink in `/etc/motd.d/insights-client` is updated to point to `/dev/null`. Additionally, the function will update the symlink to point to the actual snippet file (`/etc/insights-client/insights-client.motd`) if both registration stamp files do not exist. This enables us to make a single invocation of the function during …
> Fix motd.d management

- src/insights_client/Makefile.am
- src/insights_client/metrics.py
- src/insights_client/run.py
- src/insights_client/utc.py
This PR adds the collection of runtime metrics to the "phase runner" (`run.py`). Before each phase, an "event" object is created. The event object contains details about the phase, include start times, exit codes, exception strings, etc. It uses a specialized HTTP client (not `InsightsConnection`) so that statistics can still be reported back to the platform even in the event of a major failure of `InsightsConnection`. It keys off the RHSM server value. If it's not subscription.rhsm.redhat.com, the base URL, authentication scheme and API path prefix are configured to the "Satellite" values. If the RHSM server value is subscription.rhsm.redhat.com, then it examines the insights-client.conf authmethod value, setting up the base URL, authentication, and API path prefix values for either …
> Collect runtime statistics about phase execution

- README.md
Update README to note that `EGG` env var should point to built zip. Also document the configuration format and main section.
> REAMDE: EGG var and configuration format

- src/insights_client/Makefile.am
Files listed with the `PYTHON` primary are not subject to any build time rules. The `PYTHON` primary only does stuff during installation like byte-compile the files listed[1]. What was happening was that `constants.py` was not getting generated until necessary, and it was necessary for installation. This PR adds the `nodist_insights_client_PYTHON` sources as a `SCRIPT` primary. `SCRIPT` primaries *are* generated at build time, so this ends up generating `constants.py` earlier in the process. `SCRIPT` primaries are not distributed by default, so it doesn't need to be listed as `nodist`, and it's already not distributed via `nodist_insights_client_PYTHON`.
1: https://www.gnu.org/software/automake/manual/html_node/Python.html
2: https://www.gnu.org/software/automake/manual/html_node/Scripts.h …
> build: generate constants.py with SCRIPT primary

- src/redhat-access-insights.in
Printing the warning to stdout breaks some downstream tooling that
assumes the output of insights-client is a certain data format (such as
JSON). Instead, the warning should be printed to stderr.
Fixes: RHCLOUD-10655, RHBZ#1896547
Signed-off-by: Link Dupont <link@sub-pop.net>
> fix: print warning to stderr

- data/systemd/Makefile.am
- data/systemd/insights-checkin.service.in
- data/systemd/insights-client-checkin.service.in
- data/systemd/insights-client-checkin.timer
Created a new service for the hourly checkin and a corresponding timer unit. This PR only introduces the units, but not a mechanism to enable them upon registration. To verify their workings, launch them manually with _systemctl_ after running _make install_. Use SystemD drop-ins to change any settings.
> Check-in SystemD service

- src/insights_client/__init__.py
The insights package imported to run a Phase does not have to be an egg file. It can simply be a folder with a cloned copy of the [_insights-core_](https://github.com/RedHatInsights/insights-core/) repository. This is very common in development environments and allows to live edit and use the Core files by the Client without rebuilding the egg by making a zip file.
No tests added as this egg selecting machinery is already completely untested and adding one would be non-trivial and inconsistent.
Steps to reproduce:
1. Run the client with `EGG=/path/to/insights-core BYPASS_GPG=True insights-client --no-gpg`
2. See that the code in the folder is picked and used as the env egg, allowing for immediate edit and use of the core files without rebuilding the zip file.
> Remove egg is file condition

- configure.ac
- data/systemd/Makefile.am
Added a feature flag for the ultralight check-in SystemD units _--enable-checkin_, disabled by default. This allows us to safely ship the ultralight check-in feature without enabling it.
No tests as we don’t test autotools files.
1. _./configure_ without the flag.
2. _make_
3. Check that _data/systemd/insights-client-checkin.service_ has not been compiled.
4. _make_ install
5. Check that neither _insights-client-checkin.service_ not _insights-client-checkin.timer_ has been installed.
6. _make clean_.
7. _./configure --enable-checkin_
8. _make_
9. Check that _data/systemd/insights-client-checkin.service_ has been compiled.
10. _make_ install
11. Check that both _insights-client-checkin.service_ and _insights-client-checkin.timer_ have been installed.
12. _make clean_.
13. Check that …
> Ultralight check-in ./configure option

- data/systemd/insights-client-boot.service
Based on conversations with @subpop.  This PR will add a systemd unit file that will _upon declaration of a file run_insights_client_next_boot_ will run the insights client on the next boot of the host node.  This will be triggered by playbooks created by remediations that are specified with the `localhost` tag.
See Corresponding Remediations JIRA:  https://github.com/RedHatInsights/insights-remediations/pull/12
> Add systemd unit file for insights-client-boot service

- configure.ac
- src/insights_client/__init__.py
- src/insights_client/run.py
Reverts RedHatInsights/insights-client#136
This breaks the egg loading flow and incorrectly throws an error on the GPG verification. We'll have to revisit this change set.
> Revert "Remove egg is file condition"

- src/insights_client/__init__.py
The motd.d symlink should not be rewritten every time insights-client runs. This breaks automation that relies on the mtime of the symlink file.
Fixes RHBZ#1945481
> fix: only rewrite motd symlink if not already

- data/systemd/80-insights-register.preset
- data/systemd/80-insights.preset
- data/systemd/Makefile.am
The systemd data Makefile.am needed a bit of cleanup.
* Fixed a bug where the insights-client-checkin.service.in file was missing from the distribution tarball.
* Refactor the CLEANFILES variable to explicitly list all the files that should be cleaned up by the clean target.
* Create two preset files: one is always installed and includes insights-client-boot.service. The other is installed only if the software is configured with --enable-auto-registration, and includes the insights-register.path and insights-unregister.path units.
Fixes: RHBZ#1951750
> Various systemd/automake fixes

- src/insights_client/metrics.py
- src/insights_client/run.py
- src/insights_client/tests/test_metrics.py
Also act gracefully when
- the rhsm.conf cannot be read
- rhsm.conf _can_ be read but the cert files do not exist (i.e. system was unregistered but conf is still hanging on the disk)
> Make metrics usable without RHSM

- src/insights_client/tests/Makefile.am
_SCRIPTS_ are not distributed by default. We want to distribute tests though. Added _dist__ to the test list, so they are included.
Follow-up to #146.
> 🩹 Make metrics tests distributed

- README.md
- src/insights_client/__init__.py
* Card ID: CCT-131
* Card ID: RHEL-2480
* Card ID: RHEL-2482
GPG creates a directory $HOME/.gnupg/ every time it performs some operation. When run under root, but not manually (e.g. via subscription-manager Cockpit plugin), it tries to create and write to this directory, which causes SELinux denials.
This patch utilizes the `--homedir` argument GPG supports in order to move the home directory to a temporary directory for the time of the transaction. After the GPG action is performed, the directory is cleaned up.
This is a companion PR to https://github.com/RedHatInsights/insights-core/pull/3930 and they should be reviewed together.
> fix: Do not create /root/.gnupg/ directory by accident

- insights-client.spec
Since the BASIC authentication is deprecated, explicitly require `subscription-manager` so the CERT authentication can be used (since `auto_config` is enabled by default).
> build: require subscription-manager

- data/insights-client.conf
- insights-client.spec
This add the subpackage ros and config paramter ros_collect to insights-client.conf file to enable the ROS data collection.
Considering there could be two ways to do this and unsure about what can be accepted there is another pr https://github.com/RedHatInsights/insights-client/pull/159
> feat: add subpackage for ROS

- insights-client.spec
Ensure that the upstream packaging has all the files & directories as shipped in the RHEL packaging; in particular, ship all the empty directories in `/var`.
Also, reorder a couple of other entries to match the RHEL spec.
> build: update %files from the RHEL packaging

- src/insights_client/__init__.py
Existing SELinux rules prohibit GPG from accessing arbitrary directories, including those in /tmp/. Both tools can read/write in /var/lib/insights/ because this is where we store the eggs.
> fix(gpg): Ensure GPG can write into its temporary home directory

- insights-client.spec
Update a bit the spec file used for local builds, so it is closer to what used in RHEL:
- drop very old `redhat-access-insights`/`redhat-access-proactive` references
- use https for an URL
- fix & improve handling of `insights-client-boot.service`
Also, convert the `License` header to SPDX.
> build: update the spec file more

- integration-tests/test_status.py
- integration-tests/test_version.py
Adapt to a API change in pytest-client-tools: now commands run by the classes of the tools ("InsightsClient" in this case) are run in text mode by default.
> tests: check for strings instead of bytes

- insights-client.spec
I ended up forming the grep cmd out of new file which was just having/not having ros_collect. That resulted in completely different outcome. Below are the details about proposed fix,
The new script example,
~~~
if ! grep -q "^ros_collect" /etc/insights-client/insights-client.conf; then
cat <<EOF >> /etc/insights-client/insights-client.conf
ros_collect=True
EOF
fi
~~~
1. When ros_collect already present in file, it does not append config one more time,
~~~
ros_collect=True
ros_collect=True
~~~
2. When ros_collect is not there it adds the config,
~~~
[no output]
ros_collect=True
~~~
3. Likewise the false param stays False,
~~~
#tags_file=/etc/insights-client/tags.yaml
ros_collect=False
#tags_file=/etc/insights-client/tags.yaml
ros_collect=False
~~~
> Fix the grep command of ros postscript

- src/insights_client/__init__.py
- src/insights_client/tests/conftest.py
- src/insights_client/tests/requirements.txt
- src/insights_client/tests/test_client.py
- restore needed imports in `__init__.py`
- port away from `six`
- drop unused import in the tests config
- drop useless patches in `test_phase_error_100`
See the messages of each commit for more detailed explanations.
> Various small fixes

- configure.ac
- add "py.test", which is the old executable in pytest 3
- drop "pytest-3" and "pytest3-6", which refer to a Python 3 version (and this branch is for Python 2)
> build: update pytest executables

- src/insights_client/__init__.py
If PYTHONPATH is set to non-empty value, include it when running the egg. The Egg path is always the first to ensure the correct egg will be run, but the rest of the paths is now included.
This is useful during development. For example, `rhsm` may only be available on non-standard path (= not as installed package), and without this patch it is not possible to use it.
> fix: Respect PYTHONPATH environment

- README.md
- docs/insights-client.8
This update is a first step to address #156 it simply updates the man page and the README to clarify what the option currently does.
> Update man page and README to clarify the --group option

- systemtest/guest-setup.sh
- systemtest/tests/integration/test.sh
This will aid in downstream testing, eg: beaker, running testing-farm directly, running tmt directly, locally in a container, etc...
> feat: simulate packit setup for non-packit testing

- src/insights_client/__init__.py
1/ Improve logging; be more explicit about what is being done
2/ Remove the file instead of symlinking to /dev/null
3/ Handle situations in which the motd symlink is broken
(Updates 0ee697131b611c427986098b3c260eb5f14dc051)
> Update handling of the MOTD file

- .flake8
- .github/workflows/stylish.yml
- integration-tests/test_registration.py
- requirements-dev.txt
- src/insights_client/__init__.py
- remove extra/unused arguments in `format()` (fixes F522)
- remove an unused `import` (fixes F401)
- fix/improve the existing `.flake8` file according to the current sources
- run `flake8` in the existing `stylish` GHA workflow
See the messages of the commits for longer descriptions.
> Check the sources with flake8

- .flake8
- pyproject.toml
- src/insights-client.in
- tweak the configurations of `black` and `flake8` to handle also `src/insights-client.in` (i.e. the main executable of `insight-client`
- reformat `src/insights-client.in` with `black`
Followup of #195 and #196.
> Apply black and flake8 on src/insights-client.in

- integration-tests/conftest.py
This makes sure that the "install_katello_rpm" fixture is setup before "subman_session", and "install_katello_rpm" is tore down after "subman_session". This should ensure that the katello-ca-consumer RPM is uninstalled after "subman_session" unregisters the system.
> fix(test): use install_katello_rpm before subman_session

- integration-tests/conftest.py
- integration-tests/test_unregister.py
It should help in a situation where it is necessary to sleep for a while for a long running service to update its state.
I've applied the function in a test to present it.
> fix(test): Loop for statement

- integration-tests/test_client_options.py
This test verifies that running --checkin with --offline, a friendly message is logged, and it exists with a failure code
> Tests : added test case for --checkin with --offline client options

- systemtest/tests/integration/test.sh
This change will help failing compressor tests
because of missing bzip2 package.
> chore(test):Adding pkg bzip2 to test setup

- integration-tests/conftest.py
- integration-tests/test_client_options.py
This change will help mitigate syncup issues with
system state after registration.
Some tests intermitently fail due to slow sync.
> fix(test):added assertions to verify registered state of system

- integration-tests/test_connection.py
test failed because it did not hit the timeout value so reducing the timeout furthur to fix test.
> fix(test) : Decreased timeout value for http_timeout

- integration-tests/conftest.py
- integration-tests/requirements.txt
- integration-tests/test_display_name_option.py
There are two tests in the PR:
-  test_register_with_display_name
- test_register_twice_with_different_display_name
I've added a function 'fetch-from-inventory' to download inventory records from insights service.
I've started using subtests pytest plugin - see the second test in a list above.
subtests help me to separate logs for each part of a test. It is easier to troubleshoot a test - log messages are separated by 'subtest' message - at least.
another reason for using subtests is that a code is splitted into parts visually too.
> Tests for display-name option

- systemtest/tests/integration/main.fmf
Downstream tests now take longer than 1 hour.
> feat(test): Increase overall test time limit to two hours.

- systemtest/tests/integration/test.sh
pip fails to install fauxfactory package on s390x and ppcle64 due to dependency on cryptography package. 
Installing python3-cryptography rpm resolves the issue.
> fix(test): pip fails to install fauxfactory on s390x and ppcle

- integration-tests/requirements.txt
- integration-tests/test_display_name_option.py
- systemtest/tests/integration/test.sh
currently tests are failing to install fauxfactory on s390x and ppcle64. It is causing failure in downstream compose testing. Replacing the use of fauxfactory by using python inbuilt 'random' and 'string' modules.
Also reverting python3-cryptography that was added a package to support installation of fauxfactory. Python3-cryptography not required by any other tests
> fix(test): Removing use of fauxfactory from integration tests

- .github/workflows/pytest.yml
Fedora Rawhide (41) does not include `gpg` in its base installation.
> fix(ci): Ensure gpg is installed

- .github/workflows/pytest.yml
As of now, `fedora:latest` more or less matches c10s/el10, but they will start to diverge, and in six months they will contain different software. This is proactive measure to start testing on RHEL 10-like system.
> chore(ci): Add CentOS Stream 10 to pytest matrix

- .github/workflows/pytest.yml
CentOS Stream 8 reached EOL on 2024-05-31. This patch ensures we can still run EL8-equivalent tests on frozen version of Stream 8.
> chore(ci): Use Vault for CentOS Stream 8

- insights-client.spec
- meson_options.txt
- src/meson.build
There is no need for it anymore, so keep it only for existing enterprise
distributions.
A new `redhat_access_insights` meson option (which is false by default) is used to enable that deprecated executable.
Card ID: CCT-419
> Enable redhat-access-insights only in RHEL < 10

- integration-tests/test_obfuscation.py
register option is not considered when using --output-file option because
--output-file only runs in offline mode, so even if you pass register, system will not be registered to insights.
> fix(test): removing --register option when using ----output-file

- src/insights_client/__init__.py
* Card ID: CCT-573
`logging` does not work with field names in strings. This patch removes those to use %-formatting, which also makes it consistent throughout the method.
> fix: Make MOTD logs valid

- integration-tests/test_motd.py
- src/insights_client/tests/test_motd.py
* Card ID: CCT-414
* Card ID: CCT-415
> feat(test): Add tests for MOTD

- integration-tests/test_client.py
Test need to verify logration for insights-client-payload.log files as well.
The test was failing recently because it was only expecting insights-client.log in the log dir
which was an incorrect assumption because insights-client-payload.log files are
written in same log dir when --payload option is used
> fix(test): Updated logrotate test to verify payload log rotation too

- README.md
- docs/insights-client.8
`--force-reregister` stopped being useful in insights-core since December 2022, unconditionally erroring out since then when used. Since it is planned to be dropped altogether in insights-core [1], then drop its documentation references.
Related to: CCT-404.
[1] https://github.com/RedHatInsights/insights-core/pull/4162
> chore: drop references to --force-reregister

- src/insights_client/__init__.py
The temporary directory chosen to work properly with SELinux is `/var/lib/insights`, which can be accessed only by root.
`insights-client` is basically not usable as non-root, and it will fail with `Insights client must be run as root.`. The only exception here is `insights-client --version`, which is run only in the client without loading the core; the exception is that the client will still verify the available eggs using GPG by default.
Hence, use the default temporary directory when running as non-root: this way the available 
eggs can be validated, and the client will either
- print the version and exit
- keep exiting saying root is required
Followup of commit dd6293d608f61a44e562a1fda44cad82cf667e7d.
> fix: use system temporary directory when running as non-root

- systemtest/tests/integration/test.sh
Both the client itself and insights-core were fixed to properly do the GPG validation with new versions of gnupg; since the fixed version of insights-core is now part of the client sources, the workaround can be dropped altogether.
> test: drop manual import of GPG key

- docs/insights-client.8
The wording was not correct, mentioning incorrect instructions on what to do to not make the MOTD show up.
Hence:
- move the instructions on how to change the MOTD text to its own paragraph
- add a new paragraph about disabling the MOTD with the actual symlink needed
Fixes RHEL-50695
> doc: improve wording on MOTD file handling

- data/systemd/insights-client.service
* Card ID: CCT-463
Historically, insights-client has not been able to recover from failures that happened during its automatic execution. When the Core failed for any reason (bad code, network failure, ...), the service would stay in a 'failed' state and would not try to recover.
A few months ago, this has caused a problem that resulted in CCT-370. See https://access.redhat.com/solutions/7056526 for more details.
See the commit description for how to test this change.
> fix: Allow systemd service to restart itself on failure

- integration-tests/test_motd.py
- integration-tests/test_registration.py
Intermittently some tests fail if there is delay in host getting reflected in inventory after client performs registration, a following unregister command would fail for same reason. So adding a registration verification would help minimize such failures.
> fix(test): adding a step to verify client registration

- src/insights_client/__init__.py
* Card ID: RHINENG-11802
* Card ID: CCT-653
Ensure we get Unicode data back when we run GPG in a subshell. This will ensure we are able to parse output of the command even if the host is configured to use non-UTF-8 character set.
> fix: Run subshells with LC_ALL=C.UTF-8

- .flake8
- src/insights_client/__init__.py
- wrap/split few lines (code & comments) longer than 88
- drop no more needed per-file ignores from flake8 config
No behaviour changes, only formatting.
> chore: wrap/split long lines

- integration-tests/test_upload.py
CCT-637 - Add docstrings to test_upload.py
> feat(test): Adding betelgeuse docstrings to test_upload.py

- integration-tests/test_client.py
Adding betelgeuse docstrings to test_client.py
> feat(test): Adding betelgeuse docstrings to test_client.py

- integration-tests/test_connection.py
CT-663 - Add docstrings to test_connection.py
> feat(test): Adding betelgeuse docstrings to test_connection.py

- integration-tests/test_collection.py
CCT-661 - Add docstrings to test_collection.py
> feat(test):  Adding betelgeuse docstrings to test_collection.py

- integration-tests/test_file_workflow.py
Test to verify that change in data of files in archive updates the host data in inventory when reuploaded. I have modified the test to run from integration test perspective instead of rewriting the existing test in iqe
> test: Added test for file worflow in archive

- integration-tests/test_motd.py
> feat(test): Adding docstrings to test_motd.py

- integration-tests/test_redaction.py
> feat(test): Add docstrings to test_redaction

- integration-tests/test_checkin.py
> feat(test): Adding docstrings to test_checkin.py

- integration-tests/test_display_name_option.py
- integration-tests/test_motd.py
- "attemt" -> "attempt"
- "cerify" -> "verify"
- "informations" -> "information"
- "unchaned" -> "unchanged"
> chore: typo fixes

- integration-tests/custom_betelgeuse_config.py
Requirement is a built-in value in Polarion so while uploading the tests it failed to set up the custom value, therefore I deleted it and the upload to Polarion looks much better, more information in:
[CCT-616](https://issues.redhat.com/browse/CCT-616)
> fix(test): Changing the custom fields to enable upload to Polarion

- integration-tests/test_collection.py
- It is not required to register insights-client to run the collection. This speeds up the test.
- There is a simpler way to get a content; '--output-dir' saves the content uncompressed into user-controlled location.
- The archive may contain less content than what the test originally required.
> chore(test): Improve tests in test_collection.py

- integration-tests/test_common_specs.py
* Card ID: CCT-934
Specs that run 'hostname' or try to access special system files (e.g. /etc/fstab) fail in containers. This patch ensures spec contents are not asserted if there's no way they were collected.
> fix(test): Improve test_common_specs

- integration-tests/test_redaction.py
* Card ID: CCT-934
Containers are not in control of their own hostnames, they are usually set from the host system. Because this test runs 'hostnamectl set-hostname', it has to be skipped when we're not running on a bare metal/VM system.
> fix(test): Skip hostname redaction in containers

- integration-tests/test_display_name_option.py
* Card ID: CCT-934
insights-client usually upgrades to use non-legacy API. But with `auto_config=False`, this code isn't run and the upload to Ingress fails. We have to set this explicitly if we want to test in non-production environments.
> fix(test): Force non-legacy with auto_config=False

- integration-tests/test_connection.py
Enhancing test_http_timeout to include CCT-506 - insights-client --test-connection not catching ReadTimeoutError Exception
So far this PR is a draft as the CCT card is still in refinement
> fix(test): Enhancing test_http_timeout to include CCT-506

- systemtest/insights-core-setup.sh
* Card ID: CCT-685
This patch addresses two different problems in how we test the Core.
First, it sets the version to something very high that will never be achieved in a reasonable time. This ensures that integration tests which require version check to account for different behavior work correctly even with an egg that hasn't been built and released yet.
Second, it sets the release to '0' instead of a string. This has been breaking the version detection, since the value is usually an integer.
> fix(test): Use custom version and release for Core

- insights-client.spec
The python file/libmagic bindings are now named python3-file-magic, while python3-magic is now provided by a separate package of a PyPI module.  In any case, it does not appear that either is used in insights-clients.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2020606
> spec: remove unused python3-magic dependency

- README.md
- docs/insights-client.8
- integration-tests/test_manpage.py
* Card ID: CCT-732
The CLI includes many flags that could be reimplemented, but `conf` and `logging-file` are harder to support and offer little value to customers. Instead of removing them from the CLI, we'll remove them from the man page and document the change in the RHEL release notes, as Core is shipped to RHEL 6+ and cannot immediately remove these flags.
> docs: Undocument --conf and --logging-file

- README.md
- data/insights-client.conf
- docs/insights-client.conf.5
* Card ID: CCT-238
Since BASIC authentication has reached its EOL in insights services, it is no longer relevant or supported in the client tool. This update removes all references to BASIC authentication from the client configuration and documentation.
> docs: Remove reference to BASIC authentication

- README.md
- data/insights-client.conf
- docs/insights-client.conf.5
* Card ID: CCT-238
Since BASIC authentication has reached its EOL in insights services, it is no longer relevant or supported in the client tool. This update removes all references to BASIC authentication from the client configuration and documentation.
> [el8] docs: Remove reference to BASIC authentication

- .github/workflows/pytest.yml
This branch now only targets 'el8' and 'el9', it is not necessary to run on newer systems, as they start to diverge.
> [el8] test(ci): Drop CentOS Stream 10 and Fedora containers

- .github/workflows/pytest.yml
'master' now targets RHEL 10/CentOS Stream 10, we don't need to test these.
> [el10] test(ci): Drop CentOS 8 and 9 containers

- .github/workflows/pytest.yml
- .packit.yaml
The `el8` branch targets only EL8, so drop EL 9, EL 10, and Fedora distros from the GitHub actions and the packit config.
Card ID: CCT-1075
> [el8] ci: drop el9/10 & fedora jobs

- .github/workflows/pytest.yml
- .packit.yaml
The `el9` branch targets only EL 9, so drop EL 8, EL 10, and Fedora distros from the GitHub actions and the packit config.
> [el9] ci: drop el8/10 & fedora jobs

- integration-tests/test_checkin.py
- integration-tests/test_collection.py
- integration-tests/test_file_workflow.py
This PR fixes several tests that were failing. Some only in containers, some also for CI jobs in Jenkins.
---
This pull request is a backport of: https://github.com/RedHatInsights/insights-client/pull/324
> [el9] fix(test): Correct five failing integration tests

- integration-tests/test_motd.py
- integration-tests/test_status.py
* Card ID: CCT-1059
Status code returned by `insights-client --status` indicates whether a host is registered or not. This change updates the failing integration tests.
---
This pull request is a backport of: #337
> [el9] test: Status code indicates registration status

- integration-tests/test_motd.py
- integration-tests/test_status.py
* Card ID: CCT-1059
Status code returned by `insights-client --status` indicates whether a host is registered or not. This change updates the failing integration tests.
---
This pull request is a backport of: #337
> [el8] test: Status code indicates registration status

- systemtest/tests/integration/test.sh
DNF commands without special options do not work in image-mode, and we will have pre-prepared images with needed packaging - so we will skip executing these bits for bootc images.
Card: CCT-1183
> test: Check for bootc/image-mode deployments

- systemtest/tests/integration/test.sh
Some tests may fail on setup phase, when e.g. subscription-manager fails to register. Setting log level to debug will allow us to see logs from pytest-client-tools, and better investigate the cause for the failure.
Cherry-picked from 8f82241afe3d06e2d13748d143084d9f7f0a9138.
---
This pull request is a backport of: https://github.com/RedHatInsights/insights-client/pull/343
> [el9] chore(test): Increase pytest logging verbosity

- systemtest/tests/integration/test.sh
Some tests may fail on setup phase, when e.g. subscription-manager fails to register. Setting log level to debug will allow us to see logs from pytest-client-tools, and better investigate the cause for the failure.
Cherry-picked from 8f82241afe3d06e2d13748d143084d9f7f0a9138.
---
This pull request is a backport of: https://github.com/RedHatInsights/insights-client/pull/343
> [el8] chore(test): Increase pytest logging verbosity

- integration-tests/test_client_options.py
- integration-tests/test_collection.py
The format of collected archive is being cleaned up, with most of the
files directly in the archive root being removed or moved.
File tags.json is present twice: at /tags.json and /data/tags.json. It's
been like that for a long time, we should be able to move the path of it
to always read /data/tags.json.
By replacing --output-file with --output-dir, we can omit manipulations
with the tar file.
---
* Card ID: CCT-1198
* Card ID: RHINENG-7581
> chore(test): Update path of files collected in archive

- integration-tests/test_client_options.py
- integration-tests/test_collection.py
The format of collected archive is being cleaned up, with most of the
files directly in the archive root being removed or moved.
File tags.json is present twice: at /tags.json and /data/tags.json. It's
been like that for a long time, we should be able to move the path of it
to always read /data/tags.json.
By replacing --output-file with --output-dir, we can omit manipulations
with the tar file.
---
This pull request is a backport of: https://github.com/RedHatInsights/insights-client/pull/350
* Card ID: CCT-1198
* Card ID: RHINENG-7581
> [el9] chore(test): Update path of files collected in archive

- integration-tests/test_client_options.py
- integration-tests/test_collection.py
The format of collected archive is being cleaned up, with most of the
files directly in the archive root being removed or moved.
File tags.json is present twice: at /tags.json and /data/tags.json. It's
been like that for a long time, we should be able to move the path of it
to always read /data/tags.json.
By replacing --output-file with --output-dir, we can omit manipulations
with the tar file.
---
This pull request is a backport of: https://github.com/RedHatInsights/insights-client/pull/350
* Card ID: CCT-1198
* Card ID: RHINENG-7581
> [el8] chore(test): Update path of files collected in archive

- src/insights_client/__init__.py
Import the 'constants' module earlier in a global context: this way more things can be added to it later.
There should be no behaviour changes.
This pull request is a backport of: #353
> [el8] chore: move constants import earlier/global

- integration-tests/test_connection.py
When HTTP_PROXY environment variable is set, and is pointing at valid
proxy server, these two tests would fail because insights-client reports
different errors on network errors for proxy/non-proxy scenarios.
This code takes proxies into account, and asserts strings accordingly.
---
* Card ID: CCT-1199
> fix(test): Support running connection tests with proxy set 

- README.md
- docs/insights-client.8
* Card ID: CCT-226
Since the argument for the --diagnosis parameter was removed from insights-core code, it is no longer relevant to keep the reference to it in the documentation.
---
This pull request is a backport of: #356
> [el9] docs: Remove reference to argument for --diagnosis parameter

- README.md
- docs/insights-client.8
* Card ID: CCT-226
Since the argument for the --diagnosis parameter was removed from insights-core code, it is no longer relevant to keep the reference to it in the documentation.
---
This pull request is a backport of: #356
> [el8] docs: Remove reference to argument for --diagnosis parameter

- integration-tests/test_connection.py
When HTTP_PROXY environment variable is set, and is pointing at valid
proxy server, these two tests would fail because insights-client reports
different errors on network errors for proxy/non-proxy scenarios.
This code takes proxies into account, and asserts strings accordingly.
---
This pull request is a backport of:
- https://github.com/RedHatInsights/insights-client/pull/346
- https://github.com/RedHatInsights/insights-client/pull/362
* Card ID: CCT-1199
> [el9] fix(test): Support running connection tests with proxy set

- src/insights_client/__init__.py
Add print of insights-client version to 'if' block checking presence of valid eggs.
As whole try-except block is repeated from later code, this solution is a bit provisory.
Card ID: CCT-393
---
> fix: display insights-client version when no egg is found

- src/insights_client/tests/test_client.py
* Card ID: CCT-1220
On systems where insights-client hasn't been run yet (e.g. pure container which only has the repository and test dependencies installed), the test fails because it never gets to the mocked section.
File existence and GPG validation in 'run_phase()' are only done if 'config.gpg' is set to True; mocking the attribute to read False skips these checks.
---
- `el7` (all of RHEL 7)
> fix(test): Pass test_phase_error_100 even if no egg exists no the host

- src/insights_client/tests/test_client.py
* Card ID: CCT-1220
On systems where insights-client hasn't been run yet (e.g. pure container which only has the repository and test dependencies installed), the test fails because it never gets to the mocked section.
File existence and GPG validation in 'run_phase()' are only done if 'config.gpg' is set to True; mocking the attribute to read False skips these checks.
(cherry picked from commit 6f6337c39f9094cdd404d6a6a611160ee54822e7)
---
This pull request is a backport of: https://github.com/RedHatInsights/insights-client/pull/364
> [el9] fix(test): Pass test_phase_error_100 even if no egg exists no the host

- integration-tests/custom_betelgeuse_config.py
- integration-tests/test_checkin.py
- integration-tests/test_client.py
- integration-tests/test_client_options.py
- integration-tests/test_client_systemd.py
- integration-tests/test_collection.py
- integration-tests/test_common_specs.py
- integration-tests/test_connection.py
- integration-tests/test_display_name_option.py
- integration-tests/test_e2e.py
- integration-tests/test_file_workflow.py
- integration-tests/test_manpage.py
- integration-tests/test_motd.py
- integration-tests/test_obfuscation.py
- integration-tests/test_redaction.py
- integration-tests/test_registration.py
- integration-tests/test_status.py
- integration-tests/test_tags.py
- integration-tests/test_unregister.py
- integration-tests/test_upload.py
- integration-tests/test_version.py
- integration-tests/testimony.yml
Based on CCT-452 I have added the neccessary docstrings to the test classes and edited the testimony.yaml and custom betelgeuse config to accomodate these changes.
---
Also I am not sure, but I think we should backport it to all of our branches? So...
- `el7` (all of RHEL 7)
* Card ID: CCT-452
> fix(test): Ensure that tests are part of evidence traceability matrix.

- integration-tests/constants.py
- integration-tests/test_status.py
* Card ID: CCT-1122
Previously, certain commands (e.g., `--status`) could unintentionally trigger system unregistration if the host was missing from the Inventory. This change adds the integration test which verifies that system unregistration does not happen implicitly.
---
Since [insights-core#4354](https://github.com/RedHatInsights/insights-core/pull/4354) was merged, this PR is now ready for review.
> test: Unregistration should be always explicit

- integration-tests/custom_betelgeuse_config.py
- integration-tests/test_checkin.py
- integration-tests/test_client.py
- integration-tests/test_client_options.py
- integration-tests/test_client_systemd.py
- integration-tests/test_collection.py
- integration-tests/test_common_specs.py
- integration-tests/test_connection.py
- integration-tests/test_display_name_option.py
- integration-tests/test_e2e.py
- integration-tests/test_file_workflow.py
- integration-tests/test_manpage.py
- integration-tests/test_motd.py
- integration-tests/test_obfuscation.py
- integration-tests/test_redaction.py
- integration-tests/test_registration.py
- integration-tests/test_status.py
- integration-tests/test_tags.py
- integration-tests/test_unregister.py
- integration-tests/test_upload.py
- integration-tests/test_version.py
- integration-tests/testimony.yml
Based on CCT-452 I have added the neccessary docstrings to the test classes and edited the testimony.yaml and custom betelgeuse config to accomodate these changes.
(cherry picked from commit c69dfce6ad4c8b05dd61c83bba78fa9d0e407877)
---
This pull request is a backport of: https://github.com/RedHatInsights/insights-client/pull/374
> [el8] test: Ensure that tests are part of evidence traceability matrix

- integration-tests/test_client_options.py
* Card ID: CCT-1195
When the host is not registered to insights-client, the output for diagnosis argument should not print out 404 error message. This change updates the failing integration test.
---
This pull request is a backport of: #363
> [el9] test: Change diagnosis expected output when unregistered

- integration-tests/test_client_options.py
* Card ID: CCT-1195
When the host is not registered to insights-client, the output for diagnosis argument should not print out 404 error message. This change updates the failing integration test.
---
This pull request is a backport of: #363
> [el8] test: Change diagnosis expected output when unregistered

- integration-tests/constants.py
- integration-tests/test_status.py
* Card ID: CCT-1122
Previously, certain commands (e.g., --status) could unintentionally trigger system unregistration if the host was missing from the Inventory. This change adds the integration test which verifies that system unregistration does not happen implicitly.
---
This pull request is a backport of: #345
> [el9] test: Unregistration should be always explicit

- src/insights_client/__init__.py
Instead of showing only an error message, it should always display the client version while indicating  that the core version is not found.
* Card ID: CCT-393
This pull request is a backport of: https://github.com/RedHatInsights/insights-client/pull/341
---
> [el9] fix: display insights-client version when no egg is found

- integration-tests/requirements.txt
- integration-tests/test_client_options.py
- integration-tests/test_compliance.py
- systemtest/tests/integration/test.sh
I have added 2 tests to test the --compliance and --compliance-policies options. I also had to add some requirements as they were not on the system originally but compliance depends on them.
(cherry picked from commit 92caf53b159b7b9aa77ba6664c3015034c9e2fff)
---
This pull request is a backport of: https://github.com/RedHatInsights/insights-client/pull/378
> [el9] test: Adding tests for compliance option

- integration-tests/requirements.txt
- integration-tests/test_client_options.py
- integration-tests/test_compliance.py
- systemtest/tests/integration/test.sh
I have added 2 tests to test the --compliance and --compliance-policies options. I also had to add some requirements as they were not on the system originally but compliance depends on them.
(cherry picked from commit 12a38db30630509f774596f2cb70edbfb3ebedfd)
---
This pull request is a backport of: https://github.com/RedHatInsights/insights-client/pull/378
Card ID: CCT-1229
> [el8] feat(test): Adding tests for compliance option

- systemtest/tests/integration/main.fmf
Some of the test run failed on the timeout, so I created this PR extending the duration of the test runs to 3 hours instead of 2 to prevent failures on timeout.
---
> fix(test): Extending duration of test runs

- integration-tests/playbook_verifier/test_verifier.py
I have forgot to add the latest changes - adding the traceability docstrings and pytest tier marks into the playbook-verifier test. In this PR I'm adding these changes to test_verifier.py as an effort for CCT-1247.
---
For RHEL9 I will add these changes into the open PR so there will be no need to backporting this to the RHEL9.
Card ID: CCT-1247
> fix(test): Adding docstrings and pytest tier marks to test_verifier.py

- README.md
- docs/insights-client.8
- integration-tests/test_unregister.py
* Card ID: CCT-870
Since the command for unregistration updates only local files without calling DELETE /hosts/UUID API endpoint, integration tests must be updated accordingly.
---
Since [insights-core#4393](https://github.com/RedHatInsights/insights-core/pull/4393) was merged, this PR is ready for review.
> fix(test): --unregister does not delete inventory host

- README.md
- docs/insights-client.8
- integration-tests/test_unregister.py
* Card ID: CCT-870
Since the command for unregistration updates only local files without calling DELETE /hosts/UUID API endpoint, integration tests must be updated accordingly.
---
This pull request is a backport of: #384
> [el9] fix(test): --unregister does not delete inventory host

- README.md
- docs/insights-client.8
- integration-tests/test_unregister.py
* Card ID: CCT-870
Since the command for unregistration updates only local files without calling DELETE /hosts/UUID API endpoint, integration tests must be updated accordingly.
---
This pull request is a backport of: #384
> [el8] fix(test): --unregister does not delete inventory host

- systemtest/tests/integration/main.fmf
Some of the test run failed on the timeout, so I created this PR extending the duration of the test runs to 3 hours instead of 2 to prevent failures on timeout.
cherry-picked from b5e299125e2bb07277ff1d53617c86b6a474c6f9
---
This pull request is a backport of: https://github.com/RedHatInsights/insights-client/pull/388
> [el8] fix(test): Extending duration of test runs

- systemtest/tests/integration/main.fmf
Some of the test run failed on the timeout, so I created this PR extending the duration of the test runs to 3 hours instead of 2 to prevent failures on timeout.
Cherry-picked from b5e299125e2bb07277ff1d53617c86b6a474c6f9
---
This pull request is a backport of: https://github.com/RedHatInsights/insights-client/pull/388/
> [el9] fix(test): Extending duration of test runs

- integration-tests/playbook_verifier/test_verifier.py
Adding the traceability docstrings and pytest tier marks into the playbook-verifier test. In this PR I'm adding these changes to test_verifier.py as an effort for CCT-1247.
cherry-picked from: dd4855dd850ea6ff9e8aba759fdbf5edbdfa9179 and 3bbce1e440f706b67e4ae068c680e9debd5c1529
---
This pull request is a backport of: https://github.com/RedHatInsights/insights-client/pull/387/
> [el8] fix(test): Adding docstrings and pytest tier marks to test_verifier.py

- integration-tests/test_checkin.py
- integration-tests/test_client.py
- integration-tests/test_client_options.py
- integration-tests/test_client_systemd.py
- integration-tests/test_collection.py
- integration-tests/test_common_specs.py
- integration-tests/test_compliance.py
- integration-tests/test_connection.py
- integration-tests/test_display_name_option.py
- integration-tests/test_e2e.py
- integration-tests/test_file_workflow.py
- integration-tests/test_manpage.py
- integration-tests/test_motd.py
- integration-tests/test_obfuscation.py
- integration-tests/test_redaction.py
- integration-tests/test_registration.py
- integration-tests/test_status.py
- integration-tests/test_tags.py
- integration-tests/test_unregister.py
- integration-tests/test_upload.py
- integration-tests/test_version.py
- pytest.ini
I have added the pytest tier marks to the tests to be able to run tests from integration-tests based on the marks. I have registered the mark in the pytest.ini also. This work is being tracked in CCT-1249.
cherry-picked from: f706247afc2f9147a0ee710948bb2fed7f5243c2
---
This pull request is a backport of: https://github.com/RedHatInsights/insights-client/pull/383/
* Card ID: CCT-1249
> [el8] feat(test): Adding pytest markers for tiers

- integration-tests/test_common_specs.py
- integration-tests/test_connection.py
As part of the work done for CCT-1107 I have added the debugging options for this test to be able to catch error more efficiently in case of this test failing. We will now be able to also see why the test was actually failing and not just the error from the spec JSON. 
As a minor change I have also tried to reduce the http_timeout to make this test functional.
---
Card ID: CCT-1107
> [el8] fix(test): Adding debug options to the test_common_specs

- integration-tests/test_common_specs.py
- integration-tests/test_connection.py
As part of the work done for CCT-1237 I have added the debugging options for this test to be able to catch error more efficiently in case of this test failing. We will now be able to also see why the test was actually failing and not just the error from the spec JSON. As a minor change I have also tried to reduce the http_timeout to make this test functional.
cherry-picked from e4f09a963ae2a45063edf77be694634b479e1666
---
This pull request is a backport of: https://github.com/RedHatInsights/insights-client/pull/382
* Card ID: CCT-1237
> [el9] fix(test): Adding debug options to the test_common_specs

- integration-tests/test_common_specs.py
- integration-tests/test_connection.py
As part of the work done for CCT-1238 I have added the debugging options for this test to be able to catch error more efficiently in case of this test failing. We will now be able to also see why the test was actually failing and not just the error from the spec JSON. As a minor change I have also tried to reduce the http_timeout to make this test functional.
cherry-picked from e4f09a963ae2a45063edf77be694634b479e1666
---
This pull request is a backport of: https://github.com/RedHatInsights/insights-client/pull/382
* Card ID: CCT-1238
> fix(test): Adding debug options to the test_common_specs

- integration-tests/test_tags.py
test_tags was failing due to not having enough time for the changes to show in inventory. I have added the sleep function to wait 60 seconds before trying to get the inventory data back which then passed for me locally. This is a part of an effort for CCT-1107.
---
- `master`
Card ID: CCT-1107
> [el8] fix(test): Fixing test_tags

- integration-tests/test_tags.py
test_tags was failing due to not having enough time for the changes to show in inventory. I have added the sleep function to wait 60 seconds before trying to get the inventory data back which then passed for me locally. This is a part of an effort for CCT-1237.
(cherry picked from commit 4baa863566f694bb7b164ba939a91fa1aed20092)
---
This pull request is a backport of: https://github.com/RedHatInsights/insights-client/pull/405
Card ID: CCT-1237
> [el9] fix(test): Fixing test_tags

- integration-tests/test_file_workflow.py
- systemtest/tests/integration/test.sh
As part of a CCT-1238 I have edited 3 different tests that are connected to the archive creation / upload. I have removed the parts that are connected to inventory more than the client side and therefore we won't have to edit the tests every time core or inventory teams change something in future. It now tests the client side only - creation of the archive and that the archive is able to be uploaded. I have also added the dependecies for the bz2 compressor as the test was failing due to missing them. I have also changed checking of display_name to fqdn. This makes the test more reliable in CI environments by comparing the system's fully qualified domain name (FQDN) from the inventory instead of display_name, which can differ based on system or setup.
* Card ID: CCT-1238
---
This pull …
> fix(test): Fix archive connected tests

- integration-tests/test_file_workflow.py
- systemtest/tests/integration/test.sh
As part of a CCT-1237 I have edited 3 different tests that are connected to the archive creation / upload. I have removed the parts that are connected to inventory more than the client side and therefore we won't have to edit the tests every time core or inventory teams change something in future. It now tests the client side only - creation of the archive and that the archive is able to be uploaded. I have also added the dependecies for the bz2 compressor as the test was failing due to missing them. I have also changed checking of display_name to fqdn. This makes the test more reliable in CI environments by comparing the system's fully qualified domain name (FQDN) from the inventory instead of display_name, which can differ based on system or setup.
(cherry picked from commit …
> [el9] fix(test): Fix archive connected tests

- integration-tests/test_file_workflow.py
- systemtest/tests/integration/test.sh
As part of a CCT-1107 I have edited 3 different tests that are connected to the archive creation / upload. I have removed the parts that are connected to inventory more than the client side and therefore we won't have to edit the tests every time core or inventory teams change something in future. It now tests the client side only - creation of the archive and that the archive is able to be uploaded. I have also added the dependencies for the bz2 compressor as the test was failing due to missing them. I have also changed checking of display_name to fqdn. This makes the test more reliable in CI environments by comparing the system's fully qualified domain name (FQDN) from the inventory instead of display_name, which can differ based on system or setup.
(cherry picked from commit …
> [el8] fix(test): Fix archive connected tests

- integration-tests/test_client_options.py
- integration-tests/test_display_name_option.py
- integration-tests/test_obfuscation.py
- integration-tests/test_status.py
Updated the test_no_obfuscation_on_package_version to avoid attempting
to read directories from the archive, which was causing an AttributeError.
The test now checks only regular files and supports recursively verifying
files within directories like modules.d/. This ensures all relevant package files
are validated without errors. I also fixed test_check_results by changing the order
of the actions to give it a little time to reflect the ssh change later. The
test_display_name_option now skips if the error is SSL related as that is
a server issue and not test issue. This PR also fixes the registered only locally
test.
---
Card ID: CCT-1107
> [el8] fix(test): Fix the rest of RHEL8 tests

- integration-tests/test_common_specs.py
- integration-tests/test_tags.py
The test_tags and test_common_specs are currently not running on other architectures other than x86_64. This will need to be fixed some more in the future with better assert. For that we'll need systems not emulated but the exact architecture. Until then, as it is being worked on, we'll skip the tests for now.
---
> fix(test): Fixing some architectural differences in tests

- integration-tests/test_common_specs.py
- integration-tests/test_tags.py
The test_tags and test_common_specs are currently not running on other architectures other than x86_64. This will need to be fixed some more in the future with better assert. For that we'll need systems not emulated but the exact architecture. Until then, as it is being worked on, we'll skip the tests for now.
(cherry picked from commit eafc474ace772afd264a59958aa5fc4b9b3717a7)
---
This pull request is a backport of: https://github.com/RedHatInsights/insights-client/pull/440
> [el9] fix(test): Fixing some architectural differences in tests

- integration-tests/test_common_specs.py
- integration-tests/test_tags.py
The test_tags and test_common_specs are currently not running on other architectures other than x86_64. This will need to be fixed some more in the future with better assert. For that we'll need systems not emulated but the exact architecture. Until then, as it is being worked on, we'll skip the tests for now.
(cherry picked from commit eafc474ace772afd264a59958aa5fc4b9b3717a7)
---
This pull request is a backport of: https://github.com/RedHatInsights/insights-client/pull/440/
> [el8] fix(test): Fixing some architectural differences in tests

- integration-tests/constants.py
- integration-tests/test_ros.py
- integration-tests/testimony.yml
I have added multiple tests for insights-client-ros. I am testing all the basic functionality of ROS - these tests test that we can download the subpackage and activate the pmlogger. Then we test if the latest metrics exists once the subpaclkage is started. Then they test basic functionality of insights while ROS is installed and active and lastly that we can uninstal the subpackage and the pmlogger is inactive again. This is an effor based on the CCT-1402.
---
* Card ID: CCT-1402
> test: Adding tests for insights-client-ros

- integration-tests/playbook_verifier/test_verifier.py
- integration-tests/test_client.py
- integration-tests/test_display_name_option.py
- integration-tests/test_manpage.py
- integration-tests/test_obfuscation.py
- integration-tests/test_redaction.py
- integration-tests/test_registration.py
- integration-tests/test_upload.py
- integration-tests/testimony.yml
As a hopefully last touch to the tests in an effort to upload test runs through Betelgeuse to Polarion we need an parametrized field. It was added to the master branch in PR #415 but the changes were not backported to other branches. As it also includes changes that are no longer needed I have created this separate PR and not backport to fix this field.
(cherry picked from commit 4d4b187a5c08e337d30bfa126a804e24f2df9179)
---
This pull request is a backport of: https://github.com/RedHatInsights/insights-client/pull/448
* Card ID: CCT-1090
> [el8] fix(test): Adding parametrized option to tests

- integration-tests/test_client_options.py
- integration-tests/test_compliance.py
- integration-tests/test_display_name_option.py
Some tests were continuously failing when run against Satellite. The test_set_ansible_host_info was according to related CCT card not fixed on Satellite 6.15 and therefore should be skipped in that version. The test_compliance_policies_option was failing due to API communication troubles so in that case it will be also skipped. Based on some communications the test_display_name is not applicable on Satellite and therefore skipping it entirely if it run against it. This is the final part of CCT-1387.
---
* Card ID: CCT-1387
> fix(test): Fix Satellite failing tests

- integration-tests/test_client_options.py
- integration-tests/test_compliance.py
- integration-tests/test_display_name_option.py
Some tests were continuously failing when run against Satellite. The test_set_ansible_host_info was according to related CCT card not fixed on Satellite 6.15 and therefore should be skipped in that version. The test_compliance_policies_option was failing due to API communication troubles so in that case it will be also skipped. Based on some communications the test_display_name is not applicable on Satellite and therefore skipping it entirely if it run against it. This is the final part of CCT-1387.
(cherry picked from commit 0046638c6262a6ef6275ea9fce28718a243d8432)
---
> [el8] fix(test): Fix Satellite failing tests

- systemtest/tests/integration/test.sh
As part of testing-farm migration we need to do more test setup in this project and not Jenkins.  This exact setup is already being used by rhc.   Will need to be back-ported to all testing branches.
> moving gating rpms install from jenkins to test suite

- integration-tests/test_common_specs.py
Collection for ls_dev spec was removed from core repository, which started causing failure of integration test for this spec. This commit removes that spec from the test_common_specs.
(cherry picked from commit ab25a56f234c3fe6cf1176b9158e300fd2cf178b)
---
This pull request is a backport of: #467
> [el9] fix: Remove ls_dev from the test_common_specs

- integration-tests/custom_betelgeuse_config.py
- integration-tests/playbook_verifier/test_verifier.py
- integration-tests/test_checkin.py
- integration-tests/test_client.py
- integration-tests/test_client_options.py
- integration-tests/test_client_systemd.py
- integration-tests/test_collection.py
- integration-tests/test_common_specs.py
- integration-tests/test_compliance.py
- integration-tests/test_connection.py
- integration-tests/test_display_name_option.py
- integration-tests/test_e2e.py
- integration-tests/test_file_workflow.py
- integration-tests/test_manpage.py
- integration-tests/test_motd.py
- integration-tests/test_obfuscation.py
- integration-tests/test_redaction.py
- integration-tests/test_registration.py
- integration-tests/test_ros.py
- integration-tests/test_status.py
- integration-tests/test_tags.py
- integration-tests/test_unregister.py
- integration-tests/test_upload.py
- integration-tests/test_version.py
These fields are now injected via the Jenkins pipeline, so we don't need to define them in the integration tests and related config. This removes duplication and avoids drift between CI and the test suite.
---
> fix(test): Remove fields now provided by Jenkins pipeline

- integration-tests/constants.py
- integration-tests/test_client_systemd.py
The test was producing false positives/negatives due to complex
journal parsing and external API dependencies.
Changes:
- Replace journal monitoring with log file existence check
- Remove external API dependency causing timing issues
- Use 3-minute timer interval with 5-second delay
- Add reliable wait logic and proper cleanup
- Create constant for log file path and use helper functions consistently
This is more reliable as log file creation is direct proof of
execution without external timing dependencies.
Co-authored By: Cursor (claude-4-sonnet)
---
* Card ID: CCT-1557
> fix(test): Fix unreliable systemd timer test

- integration-tests/constants.py
- integration-tests/test_client_systemd.py
The test was producing false positives/negatives due to complex journal parsing and external API dependencies.
Changes:
- Replace journal monitoring with log file existence check
- Remove external API dependency causing timing issues
- Use 3-minute timer interval with 5-second delay
- Add reliable wait logic and proper cleanup
- Create constant for log file path and use helper functions consistently
This is more reliable as log file creation is direct proof of execution without external timing dependencies. This should solve CCT-1557.
Co-authored By: Cursor (claude-4-sonnet)
(cherry picked from commit 3f5e89e00d229f552521af8e9b6ef0b0e747bb4e)
---
This pull request is a backport of: #466
* Card ID: CCT-1557
> [el9] fix(test): Fix unreliable systemd timer test

- integration-tests/constants.py
- integration-tests/test_client_systemd.py
The test was producing false positives/negatives due to complex journal parsing and external API dependencies.
Changes:
- Replace journal monitoring with log file existence check
- Remove external API dependency causing timing issues
- Use 3-minute timer interval with 5-second delay
- Add reliable wait logic and proper cleanup
- Create constant for log file path and use helper functions consistently
This is more reliable as log file creation is direct proof of execution without external timing dependencies. This should solve CCT-1557.
Co-authored By: Cursor (claude-4-sonnet)
(cherry picked from commit 3f5e89e00d229f552521af8e9b6ef0b0e747bb4e)
---
This pull request is a backport of: #466
* Card ID: CCT-1557
> [el8] fix(test): Fix unreliable systemd timer test

- data/insights-client.conf
- docs/insights-client.conf.5
* Card ID: CCT-1576
To support the new configuration for IPv6 and MAC address obfuscation, this commit adds obfuscation_list option and removes the old obfuscate options in the configuration file. Also this commit updates manpage for the configuration file to reflect this change.
(cherry picked from commit 585fa658d2e8524fbcd2f9518445727a2b1750bc)
---
This pull request is a backport of: #495
> [el8] feat: Add obfuscation_list option to the config file

- .github/dependabot.yml
- .packit.yaml
* Card ID: CCT-1620
With the branch name changes, we need to change from where we build.
- `rhel-9-main` (RHEL >= 9.8)
> chore: Update Packit configuration for COPR builds

- .github/workflows/pytest.yml
- .packit.yaml
* Card ID: CCT-1597
This commit drops the Fedora pipelines since insights-client is not a primary tool on Fedora and is not widely supported on that platform.
---
- `rhel-10-egg` (RHEL <= 10.1)
> chore: Drop Fedora CI configuration

- integration-tests/test_client_options.py
- integration-tests/test_collection.py
- integration-tests/test_connection.py
- integration-tests/test_motd.py
- integration-tests/test_status.py
- integration-tests/test_version.py
Accommodate changes to InsightsClient.run() which now uses runcon by default to execute insights-client with insights_client_t SELinux context, matching production systemd behavior.
Updated user-invoked functionality tests to use selinux_context=None:
- test_version.py: --version command (1 call)
- test_client_options.py: --support, --validate, and unregistered --diagnosis (3 calls)
- test_connection.py: all --test-connection calls (5 calls)
- test_status.py: all --status calls (3 calls)
- test_motd.py: --status calls for MOTD testing (2 calls)
- test_collection.py: --verbose for timeout configuration testing (1 call)
Production/service functionality tests (registration, upload, compliance, data collection) retain default SELinux context to match systemd behavior.
This ensures tests …
> [rhel-8-egg] feat(test): Add selinux_context=None for user-invoked functionality tests

- src/insights_client/__init__.py
* Card ID: CCT-1632
The logic for changing SELinux context at runtime should not apply when running as unconfined_service_t. This context is active when insights-client is run as a systemd daemon: during automatic registration, when executed via rhc-worker-playbook.
(cherry picked from commit 8c9f44c482a10bdc6bd12a311db815532bfbd08d)
---
This pull request is a backport of: #521
> [rhel-9-main] fix: Do not switch context when running as unconfined_service_t

- src/insights_client/__init__.py
* Card ID: CCT-1632
The logic for changing SELinux context at runtime should not apply when running as unconfined_service_t. This context is active when insights-client is run as a systemd daemon: during automatic registration, when executed via rhc-worker-playbook.
(cherry picked from commit 8c9f44c482a10bdc6bd12a311db815532bfbd08d)
---
This pull request is a backport of: #521
> [rhel-10-egg] fix: Do not switch context when running as unconfined_service_t
