RedHatInsights/insights-client

- etc/insights-client.spec
Remove the executable permission from the following files:
* /etc/insights-client.conf
* /etc/*.pem
* /etc/insights-client/rpm.egg.asc
* /etc/ansible/facts.d/insights.fact
* /etc/ansible/facts.d/insights_machine_id.fact
> change permission for pem, conf, and fact files

- etc/insights-client.spec
This sets the cron schedule by default when the RPM is installed
> Create cron file when RPM is installed

- insights_client/__init__.py
See https://github.com/RedHatInsights/insights-core/pull/434
> Add pre and post update phases

- insights_client/__init__.py
See https://github.com/RedHatInsights/insights-core/pull/461 for corresponding core changes.
> Expect phase to always return JSON on stdout

- etc/insights-client.spec
Remove the cron installation from the RPM so we can move it to the register steps. Also fix permissions on rpm.egg so they are world readable
> Fix permissions on rpm.egg and remove cron installer

- etc/insights-client.spec
I found I couldn't run `insights-client` as anyone but root.  @SteveHNH can you review these permission changes in case I opened something up I shouldn't have?
> Give world read perms to site-package files

- insights_client/__init__.py
- insights_client/run.py
This allows us to support multiple versions of the phase functions simultaneously in one egg.
Please merge in lockstep with https://github.com/RedHatInsights/insights-core/pull/505
> Load phase functions from new module

- etc/insights-client.spec
%post issues "1" on initial installation and "2" on upgrade for "$1." We want to perform any necessary migration steps on an initial installation of "insights-client" as this indicates we are probably moving from "redhat-access-insights" to "insights-client."
> check for initial installation

- etc/insights-client.cron
- max 30% of one cpu
- max 2G memory+swap (i.e. no swapping allowed)
- 1G memory soft limit
- set blkio to lowest priority (100)
- add 10m timeout
> Add new runtime constraints in cron file

- insights_client/__init__.py
This fixes issue #54.
- Add GPG verification code (instead of relying on code from egg)
- Enable bypass via environment variable.  This only applies to the GPG
verification done in the parent process; eggs loaded in subprocess (i.e.
phases) still use --no-gpg.
- If last_stable.egg cannot be GPG verified, try rpm.egg.  If rpm.egg is
verified, use it instead of last_stable.egg.  If rpm.egg cannot be
verified, either, then print an error message and exit.
- A debug logging statement is added after logging has been set up to
indicate which egg was loaded in the parent process.
Look for string: "Loaded initial egg".
> GPG verify egg in parent process

- etc/insights-client.spec
- insights_client/__init__.py
- insights_client/constants.py
- also change macros in specfile for RHEL 6 compat
> figure out whether rpm.egg or last_stable.egg is newer and use that one

- docs/insights-client.8
The bold code was wrong on this line.
> Fix bolding in manual page

- etc/insights-client.cron
- etc/insights-client.service
- etc/insights-client.timer
Document each systemd unit and cron script, directing users how and where to perform modifications.
Signed-off-by: Link Dupont <link@sub-pop.net>
> Add documentation about how to override variables

- Makefile
- etc/insights-client.spec
- insights_client/constants.py
These are the build system changes necessary to release 3.0.10.
> Actually minor build system updates

- docs/file-content-redaction.yaml.example
Hey I'd like to start adding real world examples to this file based on what we see from the product team.
If we start to grow this a some we should probably add tests and such for the examples perhaps... but this is an easy start.
> Adding a few "real world" examples to the redactions conf

- data/systemd/insights-client-results.service.in
> systemd: do not sleep when running "check-results"

- src/insights_client/__init__.py
- src/insights_client/run.py
Remove the shebangs from `__init__.py` and `run.py`.
> remove shebangs from local files

- docs/insights-client.8
Added _--checkin_ documentation to the manual page.
https://issues.redhat.com/browse/RHCLOUD-11884
> Add checkin option to documentation 📝

- src/insights_client/tests/test_metrics.py
These are suggestions from a #146 review after it got merged.
- Formatted the file to be more PEP 8 compliant.
- Added test cases for offline switch overrides.
- Leveraged unittest.mock’s Mock initialization.
- DRIED missing credentials tests by parametrization.
> ♻️✅ Refactor metrics tests a bit

- insights-client.spec
It was inserted halfway between the main package %postun scriptlet by mistake.
> Fix location of ros %postun scriptlet

- insights-client.spec
Only build the ros subpackage when rpmbuild is invoked with the "--with ros" flag.
> Conditionally build ros subpackage

- .github/workflows/pytest.yml
- src/insights_client/__init__.py
This set of commits makes it easier to read the code and to debug any problems that may exist during runtime. See individual commit descriptions for details.
This PR should not be introducing any behavioral changes.
> Easier maintenance and debugging

- src/insights_client/__init__.py
> fix(gpg): Try to shutdown GPG agent before removing its home directory

- src/insights_client/__init__.py
Show each egg finish; successful or not.
> fix: Improve debugging connected to eggs

- integration-tests/test_registration.py
> feat(test): Add tests for registration and unregistration

- integration-tests/requirements.txt
- integration-tests/test_client_options.py
- integration-tests/test_obfuscation.py
- integration-tests/test_registration.py
https://gitlab.cee.redhat.com/insights-qe/iqe-insights-client-plugin/-/blob/master/iqe_insights_client/tests/test_satellite.py
> Test: add test cases for insights-client with satellite

- integration-tests/test_client.py
- integration-tests/test_obfuscation.py
- integration-tests/test_status.py
Changing the way we assert insights is registered in failing tests
> fix(test): Changing the way we assert insights is registered

- integration-tests/test_registration.py
Edited one tests to better suit the CCT-161 latest changes and created 2 more tests to test CCT-161
> Adding tests to insights-client/test_registration

- integration-tests/test_manpage.py
Migrating test_manpages.py upstream
> feat(test): Adding a test for manpage

- integration-tests/test_client_options.py
Migrating no_upload_test.py upstream
> feat(test): Migrating no_upload_test.py upstream

- integration-tests/test_client_options.py
Added tests for --support and --group option. Basically migrated tests from iqe-insights-client-plugin .
> Tests: added tests for --group and --support client option

- integration-tests/test_connection.py
Migrating test_connection.py upstream
> feat(test): Migrating test_connection.py upstream

- integration-tests/test_checkin.py
when performing --checkin operation, it updates the "stale_timestamp" and "updated" host values.
> Test : Added test for ultra-light checkin, --checkin operation

- integration-tests/test_client_options.py
Tests : Added test for --diagnosis option
> Tests : Added test for --diagnosis option

- integration-tests/test_upload.py
1- test to verify that a pre-collected insights-archive can be uploaded 
2- test to verify wrong content-type
3- test to verify upload of a very large file
> test : Added test for --payload option to upload archives

- integration-tests/test_upload.py
This test verifies that valid compressor types(gz,bz2,xzwq) can be used to generate archive and upload using --payload option.
> test: Added test for --compressor

- integration-tests/test_upload.py
Adding two tests to verify that retry is attempted when upload fails and not attempted when failure is due to unrecoverable reasons.
> test: added test for --retry option during failed uploads

- integration-tests/test_client.py
Migrating test_reg.py upstream with slight changes to the original test
> feat(test): Migrating test_reg.py upstream

- integration-tests/test_client_options.py
Migrating test_check_results.py upstream
> feat(test): Migrating test_check_results.py upstream

- integration-tests/test_collection.py
migrating test cases for --output-dir and --output-file, both positive and negative testcases
> test : migrating tests cases from test_collection.py

- integration-tests/constants.py
- integration-tests/test_checkin.py
that variables will be used in other tests. 
So I've moved the var into shared file.
> refactor: how to manage shared variables (aka HOST_DETAILS)

- integration-tests/test_common_specs.py
Migrating test_common_specs.py upstream
> feat(test): Migrating test_common_specs.py upstream

- integration-tests/test_common_specs.py
This commit will help fix coding/programming error in this test.
> fix(test): fixed failing test test_common_spec

- integration-tests/constants.py
- integration-tests/test_registration.py
The PR provides tests for register command.
> test: Adding tests for register operation

- integration-tests/test_collection.py
migrating test_cmd_timeout, test_archive_structure and test_branch_info
> feat(test): Migrating tests from test_collection.py upstream

- integration-tests/test_file_workflow.py
Adding test to verify file workflow when uploading archive without cannonical facts and with only one cannoical fact
> test : Migrating test_file_workflow.py

- data/insights-client.motd
This patch aims to improve the registration
instructions provided to users in the insights motd. 
The new messages focus on directing the user
to registering with 'rhc' and related KAs.
Resolves: CCT-264
> feat: improves motd registration instructions

- src/insights_client/__init__.py
[CCT-372](https://issues.redhat.com/browse/CCT-372)
This pull request improves the debugging experience of the the egg selection and core initialization process by adding more verbosity. It is now clear what egg has been selected, what commands are used to run the core phases as well as what happend in case of an error. GPG verfification is verbosely logged, too.
A proper logger is initialized instead of using bare prints. It uses the same message format as the core and is controlled by the same CLI flags (`--verbose` and `--silent`) and corresponding environment variables. All log statements are called in a unified way. The temporary logger is torn down just before the core initializes its own one.
Steps to verify:
1. Run the client with a `--verbose` flag.
```
```
3. See the messages …
> feat: Debug initialization

- integration-tests/playbook_verifier/playbooks/README.md
- integration-tests/playbook_verifier/playbooks/compliance_openscap_setup.yml
- integration-tests/playbook_verifier/playbooks/insights_setup.yml
- integration-tests/playbook_verifier/test_verifier.py
> test: Add integration tests for the Ansible playbook verifier

- integration-tests/conftest.py
- integration-tests/test_checkin.py
- integration-tests/test_client.py
- integration-tests/test_client_options.py
- integration-tests/test_collection.py
- integration-tests/test_display_name_option.py
- integration-tests/test_file_workflow.py
- integration-tests/test_registration.py
- integration-tests/test_status.py
I read all tests and I updated them to use loop_until statement when it makes sense.
I have tested it and fixed a few errors.
> added loop_until statement into tests

- systemtest/copr-setup.sh
- systemtest/tests/integration/test.sh
Adding script to install from copr/packit build for downstream PR jobs. Fixes CCT-572
> feat(test): Install copr build on donwstream PR jobs

- .gitleaks.toml
- systemtest/insights-core-setup.sh
- systemtest/tests/integration/test.sh
Install insights-core if a branch of it is specified. This will sign it with a test gpg key and place the egg in the proper location
> feat(test):  Allow CI to install insights-core

- README.md
- src/insights_client/__init__.py
- "instantation" -> "instantiation"
- "proces" -> "process"
Found using codespell.
> chore: typo fixes

- integration-tests/test_client_systemd.py
Added a test case to run data collection and upload via systemd timer
> test: Added test to trigger insights-client via insights-client.timer

- systemtest/tests/integration/test.sh
> feat(test): Saving test artifacts from a tmt run

- integration-tests/test_client_options.py
> feat(test): Adding docstrings to test_client_options.py

- integration-tests/test_common_specs.py
> feat(test): Adding docstrings to test_common_specs.py

- integration-tests/test_registration.py
> feat(test): Adding docstrings to test_registration.py

- integration-tests/test_manpage.py
> feat(test): Adding docstrings to test_manpage.py

- integration-tests/test_obfuscation.py
> feat(test): Adding docstrings to test_obfuscation 

- integration-tests/test_display_name_option.py
> feat(test): Adding docstrings to test_display_name_option.py 

- integration-tests/test_status.py
> feat(test): Adding docstrings to test_status.py

- integration-tests/test_unregister.py
> feat(test): Adding docstrings to test_unregister.py

- integration-tests/custom_betelgeuse_config.py
- integration-tests/test_checkin.py
- integration-tests/test_client.py
- integration-tests/test_client_options.py
- integration-tests/test_collection.py
- integration-tests/test_common_specs.py
- integration-tests/test_connection.py
- integration-tests/test_display_name_option.py
- integration-tests/test_file_workflow.py
- integration-tests/test_manpage.py
- integration-tests/test_motd.py
- integration-tests/test_obfuscation.py
- integration-tests/test_redaction.py
- integration-tests/test_registration.py
- integration-tests/test_status.py
- integration-tests/test_unregister.py
- integration-tests/test_upload.py
- integration-tests/test_version.py
More information:
https://redhat-internal.slack.com/archives/C04BQU91DQC/p1728382699258569
> feat(test): Changing tier to tags for Polarion reasons

- .github/workflows/codespell.yml
Add a simple workflow to run codespell as part of the checks for every PR.
> ci: add workflow for codespell

- integration-tests/test_checkin.py
- integration-tests/test_collection.py
- integration-tests/test_file_workflow.py
This PR fixes several tests that were failing. Some only in containers, some also for CI jobs in Jenkins.
---
This pull request is a backport of: https://github.com/RedHatInsights/insights-client/pull/324
> [el8] fix(test): Correct five failing integration tests

- .packit.yaml
'master' targets only EL 10 and Fedora.
Card ID: CCT-1074
> ci: drop EL 8 & 9 distros from packit

- systemtest/tests/integration/test.sh
Cherry-picked from 287c92f9efcc374970cfb414800249c81308e512.
---
This pull request is a backport of: https://github.com/RedHatInsights/insights-client/pull/340
> [el9] test: Check for bootc/image-mode deployments

- integration-tests/test_connection.py
Amends 4996580788e15a10ca471abdf077736db69f76d9 with a fix to properly handle subscription-manager proxy configuration.
---
- `el9` (all of RHEL 9): https://github.com/RedHatInsights/insights-client/pull/358
- `el8` (all of RHEL 8): https://github.com/RedHatInsights/insights-client/pull/357
* Card ID: CCT-1199
> fix(test): Properly read rhsm.conf proxy

- integration-tests/test_client_options.py
* Card ID: CCT-1195
When the host is not registered to insights-client, the output for diagnosis argument should not print out 404 error message. This change updates the failing integration test.
---
Since [insights-core#4366](https://github.com/RedHatInsights/insights-core/pull/4366) was merged, this PR is now ready for review.
> test: Change diagnosis expected output when unregistered

- integration-tests/requirements.txt
- integration-tests/test_client_options.py
- integration-tests/test_compliance.py
- systemtest/tests/integration/test.sh
---
I have added 2 tests to test the --compliance and --compliance-policies  options. I also had to add some requirements as they were not on the system originally but compliance depends on them.
* Card ID: CCT-1229
> feat(test): Adding tests for compliance option

- integration-tests/requirements.txt
---
- `el7` (all of RHEL 7) ?
* Card ID: CCT-1208
> test(deps): updating location of pytest-client-tools

- integration-tests/requirements.txt
cherry pick of https://github.com/RedHatInsights/insights-client/pull/391
> [el9] test(deps): updating location of pytest-client-tools

- docs/insights-client.8
* Card ID: CCT-869
Since the status command checks only the presence of .registered file without calling Insights API, documentation must be updated accordingly.
(cherry picked from commit f9044ac00aeae0eca0cec47646986f2a1ec65e3f)
---
This pull request is a backport of: #399
> [el9] docs: --status checks the presence of .registered file

- docs/insights-client.8
* Card ID: CCT-869
Since the status command checks only the presence of .registered file without calling Insights API, documentation must be updated accordingly.
(cherry picked from commit f9044ac00aeae0eca0cec47646986f2a1ec65e3f)
---
This pull request is a backport of: #399
> [el8] docs: --status checks the presence of .registered file

- systemtest/insights-core-setup.sh
This will allow the automation to use prebuilt insights-core-eggs from different repos
* Card ID: CCT-1022
> feat(ci): use prebuilt core eggs

- docs/file-redaction.yaml.example
> [el9] fix(docs/file-redaction.yaml.example): remove a tab char causing a trouble

- systemtest/tests/integration/test.sh
> [el9] feat(ci): moving gating rpms install from jenkins to test suite

- integration-tests/test_client.py
Based on the change in CCT-1082 the insights-client details file should not get recreated after the --check-results option. I have therefore edited the test to reflect that change so the test does not fail.
---
* Card ID: CCT-1082
> fix(test): Fix insights-client details file test

- integration-tests/test_client.py
Based on the change in CCT-1082 the insights-client details file should not get recreated after the --check-results option. I have therefore edited the test to reflect that change so the test does not fail.
(cherry picked from commit 41f2f2b3099997f79aaf7795a5d899bab8662363)
---
This pull request is a backport of: #456
> [el8] fix(test): Fix insights-client details file test

- src/insights_client/__init__.py
To make it possible to debug transitions into- and from `insights_core_t` context, provided by `insights-core-selinux`, this patch adds information about SELinux status and its changes.
---
- `rhel-9-main` (RHEL 9.8+)
> feat: Add SELinux related logging

- src/insights_client/__init__.py
To make it possible to debug transitions into and from `insights_core_t` context, provided by `insights-core-selinux`, this patch adds information about SELinux status and its changes.
(cherry picked from commit 94d46ce402945dcaeaa0561e08945cfc15782b7a)
This pull request is a backport of: #460
> [rhel-10-egg] feat: Add SELinux related logging

- src/insights_client/__init__.py
To make it possible to debug transitions into and from `insights_core_t` context, provided by `insights-core-selinux`, this patch adds information about SELinux status and its changes.
(cherry picked from commit 94d46ce402945dcaeaa0561e08945cfc15782b7a)
This pull request is a backport of: #460
> [rhel-9-egg] feat: Add SELinux related logging
